extern bool allow_scanning;
extern float current_X;
extern float current_Y;
extern float current_angle;
extern float delta_dist;
extern float delta_angle;
extern char current_cmd;
extern float current_cmd_val;
extern int has_moved;
extern float previous_min_angle;
extern float previous_dist_180_degree;
extern float previous_dist_0_degree;
extern int g_argc;
extern const char ** g_argv;
